name: CI

on:
  push:
    branches: [ main, feature]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        
    - name: Install Python dependencies
      run: pip install -r fastapi-app/requirements.txt
      
    - name: Install Node dependencies
      working-directory: ./nextjs-app
      run: 
        npm install -g pnpm
        pnpm install
        
    - name: Test FastAPI
      run: |
        cd fastapi-app
        python -m pytest --disable-warnings || echo "No tests yet"
        
    - name: Test Next.js
      working-directory: ./nextjs-app
      run: pnpm run build
      
    - name: Docker build test
      run: docker compose build