name: Deploy to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # 手動実行を追加

env:
  ACR_NAME: acrfastapicademo
  RESOURCE_GROUP: rg-fastapi-ca-demo
  FASTAPI_APP_NAME: ca-fastapi-demo
  NEXTJS_APP_NAME: ca-nextjs-demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Login to ACR
      run: az acr login --name ${{ env.ACR_NAME }}
      
    - name: Ensure Container Apps ACR Registry Configuration
      run: |
        # FastAPI Container App のレジストリ設定確認・設定
        echo "Configuring FastAPI Container App registry..."
        az containerapp registry set \
          --name ${{ env.FASTAPI_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --server ${{ env.ACR_NAME }}.azurecr.io \
          --username ${{ env.ACR_NAME }} \
          --password $(az acr credential show --name ${{ env.ACR_NAME }} --query passwords[0].value -o tsv) || echo "FastAPI registry already configured"
        
        # Next.js Container App のレジストリ設定確認・設定
        echo "Configuring Next.js Container App registry..."
        az containerapp registry set \
          --name ${{ env.NEXTJS_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --server ${{ env.ACR_NAME }}.azurecr.io \
          --username ${{ env.ACR_NAME }} \
          --password $(az acr credential show --name ${{ env.ACR_NAME }} --query passwords[0].value -o tsv) || echo "Next.js registry already configured"
      
    - name: Build and push FastAPI
      run: |
        IMAGE_TAG="main-${{ github.sha }}"
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/fastapi:$IMAGE_TAG \
          --file fastapi-app/Dockerfile ./fastapi-app
        docker push ${{ env.ACR_NAME }}.azurecr.io/fastapi:$IMAGE_TAG
          
    - name: Build and push Next.js
      run: |
        IMAGE_TAG="main-${{ github.sha }}"
        docker build -t ${{ env.ACR_NAME }}.azurecr.io/nextjs:$IMAGE_TAG \
          --file nextjs-app/Dockerfile ./nextjs-app
        docker push ${{ env.ACR_NAME }}.azurecr.io/nextjs:$IMAGE_TAG
          
    - name: Deploy FastAPI to Container Apps
      run: |
        IMAGE_TAG="main-${{ github.sha }}"
        az containerapp update \
          --name ${{ env.FASTAPI_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image ${{ env.ACR_NAME }}.azurecr.io/fastapi:$IMAGE_TAG
          
    - name: Deploy Next.js to Container Apps
      run: |
        IMAGE_TAG="main-${{ github.sha }}"
        az containerapp update \
          --name ${{ env.NEXTJS_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image ${{ env.ACR_NAME }}.azurecr.io/nextjs:$IMAGE_TAG
          
    - name: Verify deployment
      run: |
        echo "Waiting for deployment to complete..."
        sleep 60
        
        # FastAPI health check
        FASTAPI_URL=$(az containerapp show --name ${{ env.FASTAPI_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv)
        curl -f https://$FASTAPI_URL/docs || echo "FastAPI health check failed"
        
        # Next.js health check
        NEXTJS_URL=$(az containerapp show --name ${{ env.NEXTJS_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --query properties.configuration.ingress.fqdn -o tsv)
        curl -f https://$NEXTJS_URL || echo "Next.js health check failed"
        
        echo "FastAPI URL: https://$FASTAPI_URL"
        echo "Next.js URL: https://$NEXTJS_URL"